### ISSUE TITLE
Install asciicast2gif via brew and/or npm -g

### ISSUE THREAD

**Issue by alexkuz** [asciinema/asciicast2gif#18]
Using docker image is a nice option, but it would be even better to be able to install it via brew or npm (since it's already a npm package).

Thank you for a great tool!

**Comment by sickill** [comment]
Yeah, I agree having a proper npm package would be nice.

Publishing to npmjs.org would probably only require small tweak to `package.json`, so that ClojureScript compiled `main.js` and `page/page.js` files are included in the package.

I would happily accept a PR if anyone is willing to attack this.
