### ISSUE TITLE
"no space left on device" when running in Docker

### ISSUE THREAD

**Issue by christopher-dG** [asciinema/asciicast2gif#30]
Following the Docker example in the readme I get this "no space left" error, when my disk has > 200GB remaining:

```sh
[ ~/Downloads ] docker run --rm -v $PWD:/data asciinema/asciicast2gif -t solarized-dark 134369.json demo.gif
==> Loading 134369.json...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining screenshots into GIF file...

convert: unable to write pixel cache `/tmp/magick-26AFqOawtyXtYw': No space left on device @ error/cache.c/WritePixelCachePixels/5492.
==> Done.
```

The asciicast itself is 35 seconds long. [Here](https://pastebin.com/jArmFQpi) is the content of my JSON file, for reference.

**Comment by sickill** [comment]
That's interesting. Maybe the image has `/tmp` mounted to some small, fixed sized block device... 🤔

**Comment by dzonerzy** [comment]
Same here with > 30GB

**Comment by sickill** [comment]
I've implemented some optimizations:

- the biggest impact on resource usage was too high frame-rate - it's capped at 15fps now
- added support for giflossy (if giflossy is installed instead of gifsicle the options passed to gifsicle command are extended with `-lossy=80`)

I've pushed new version to npm, and there's new image on Docker hub (`docker pull asciinema/asciicast2gif` if you previously pulled it).

You can set `GIFSICLE_OPTS` env var to override the options passed to gifsicle, which is great for experimenting with different color/optimization/lossyiness combinations.

Let me know if that helped!

**Comment by ku1ik** [comment]
Please try asciicast2gif's successor - https://github.com/asciinema/agg

I took @christopher-dG original recording, converted it to asciicast v2 format, then used `agg` to generate gif file:

![demo-opt](https://user-images.githubusercontent.com/17589/184534217-9cfc8600-10fe-4703-a653-d236331bd764.gif)

It took 3 seconds to generate it with agg!
