### ISSUE TITLE
asciinema doesn't capture ncurses box

### ISSUE THREAD

**Issue by xdb64** [asciinema/asciicast2gif#64]
I recorded a [snake game session](https://github.com/adder46/snake/blob/master/snake.gif), however it seems that asciinema doesn't capture ncurses box.

It would be nice if asciinema could do that.

**Comment by ku1ik** [comment]
I'm not sure what was the problem here... but I used your minimal example and generated gif with asciicast2gif's successor - https://github.com/asciinema/agg - and the result looks alright to me:

![vQwSCQOOdbVpdupfrJSFBoEHe](https://user-images.githubusercontent.com/17589/184548682-7dff6a42-1d17-4f6e-888d-5f3fc92e5256.gif)

In the future I suggest to use `agg` instead, as asciicast2gif will no longer be maintained.
