### ISSUE TITLE
[FR] Add option to specify working/tmp directory

### ISSUE THREAD

**Issue by AndydeCleyre** [asciinema/asciicast2gif#71]
`0.2.1`

As it is, it takes the liberty of using my RAM-based `/tmp`, then proceeds to use all my swap space, followed by melting my house down. I am unable to use this unless I can specify a directory for all those frames. Even then, it would be nice to offer some estimate of space required.

**Comment by mathieu-aubin** [comment]
You should check out this code i just finished. Honestly, i didn't have much time but when i saw your request, i figured it wasn't something hard to implement, even at the most basic of levels.

I also added lots of comments... set the scale to 1 by default in order to reduce the size and time it takes to generate the gifs. The way its currently being done isn't optimum but... 

https://github.com/mathieu-aubin/asciicast2gif/blob/master/asciicast2gif

you could install with npm and using my repo url. If you think this could be worthy of a pull request, let me know and i will open one.

Also, DEBUG will print some extra infos and will NOT delete the temporary directory. This could be useful in case you wanted to optimize all the png files and recompress your own gif/webp from the output of this

https://github.com/mathieu-aubin/asciicast2gif

**Comment by ku1ik** [comment]
Try https://github.com/asciinema/agg instead. It doesn't use any tmp space on disk.
