### ISSUE TITLE
[why?]

### ISSUE THREAD

**Issue by gerrywastaken** [asciinema/asciicast2gif#80]
I read the README but I'm still left wondering what benefit this provides. I figure there is likely some reason as quite a lot of people are using this to convert Asciicinema files to less accessible gifs. I wish to know the use case as I currently see it like this..

Asciicinema casts can:

1. Be paused (even in a browser)
2. Have a seek bar (even in a browser)
3. Can be set to full scree (even in a browser)
4. Show a timestamp
5. Unlike gifs its simple to know where they start and end
6. Allows selecting and copying text from the cast
7. Allows screen readers and blind people to access the content
8. The file can be replayed in a terminal
9. The file can be downloaded and parsed by a script as it's just text

Converting `.cast` files to gifs appears to take away all this accessibility and I'm not sure what the upside is. Perhaps the reasoning could be added to the Readme?

**Comment by worldofprasanna** [comment]
@gerrywastaken I use `asciicast2gif` always with `Asciicinema` because having gif with autostart is easy to read in Github Readme 's, Twitter / LinkedIn / Blog posts. I am not aware of a method to directly using Asciicinema links in these places

**Comment by SkypLabs** [comment]
> @gerrywastaken I use `asciicast2gif` always with `Asciicinema` because having gif with autostart is easy to read in Github Readme 's, Twitter / LinkedIn / Blog posts. I am not aware of a method to directly using Asciicinema links in these places

Same here. It is also useful for GitHub repositories' social media previews. I just submitted an issue about it to improve the rendering: #82.

**Comment by sickill** [comment]
I created asciinema because I felt that using screen recording software which outputs mp4 or even gif is too heavy weight, and I also wanted it to be super easy. But it turns out that lots of people want gif for some reason, while at the same time they appreciate the ease of starting a recording from inside your terminal. I myself don't use asciicast2gif, but many people do. So there's something for everybody :)

**Comment by mathieu-aubin** [comment]
how is gif 'less accessible ' ? CLI usage is what i see but other than that... im wondering

**Comment by gerrywastaken** [comment]
> how is gif 'less accessible ' ? CLI usage is what i see but other than that... im wondering

@mathieu-aubin I outlined a list of 9 items at the very top of the thread. I'm not sure what else I can say.

**Comment by gerrywastaken** [comment]
@sickill Thank you for responding and creating asciinema :heart: 

> But it turns out that lots of people want gif for some reason, while at the same time they appreciate the ease of starting a recording from inside your terminal. 

From the two responses, it seems people use this simply because they can't embed asciicasts directly any other way. However, I believe they are also unaware of the huge downsides of doing so, especially as these downsides are not outlined in the asciicast2gif readme.

> I myself don't use asciicast2gif, but many people do. So there's something for everybody :)

You say "something for everybody" but this project to convert an accessible format to an unaccessible format is widely used and is actually contributing to taking away accessibility from many people around the world. Without such warnings to the downsides and recommendations to add a link to the cast below the gif, I feel this project does more harm than good in its current implementation and is encouraging the conversion to gifs and severely downplaying the advantages of the cast format.

**Comment by mathieu-aubin** [comment]
> ... I outlined a list of 9 items at the very top of the thread. I'm not sure what else I can say ...

@gerrywastaken I saw, yes. It seemed to me that you listed advantages of 'something' having very little to do with a file format. Yes, i can agree ... gif doesn't have 'functions' per say, it is a file format after all.

You compared it to a complete, purpose-built, feature-rich 'something' that writes and reads itself based on specific instructions rather than a standard for which _litterally everything_ nowadays is compatible with. I figured the simple fact of having to have 'dependencies', some install procedure and specific usage parameters made asciinema the actual 'less accessible' solution. I certainly don't mean it's not practical or whatever. Your observations are correct, as intended by the 'program/software' design and stated as features.

I guess i got hung up on the wording, which i still think is inacurrate (who am i to know, really??), but i understand your point and what you meant by that. Hopefully you get my 'confusion'. If not, well... it won't be the first time i live in my own world!

i'm no english guru, in fact it's clearly not my first language and i didn't want to pretend to be even good at it. I manage, at best. And also, sorry for maybe repeating or over-explaining how i saw the whole thing and why i asked originally... i wanted to make sure i had a chance at explaining without giving off pretentious vibes - i suck at most what i do and ask questions so i can better refine my knowledge and ideology.
